version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: cloud-bridge-postgres
    restart: always
    environment:
      POSTGRES_USER: cloudbridge
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_bridge
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.18.0
    container_name: cloud-bridge-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: cloud-bridge-es
    environment:
      - node.name=cloud-bridge-es
      - cluster.name=cloud-bridge-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
